name: Build LaTeX CV

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Récupérer ton code
      - name: Checkout du dépôt
        uses: actions/checkout@v3

      # 2️⃣ Installer une version minimale de TeXLive + les paquets nécessaires
      - name: Installer LaTeX minimal
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-latex-base texlive-latex-extra texlive-fonts-recommended texlive-lang-french latexmk

      # 3️⃣ Compiler avec latexmk (plus sûr que pdflatex)
      - name: Compiler le CV
        run: |
          latexmk -pdf -interaction=nonstopmode -halt-on-error -file-line-error cv.tex

      # 4️⃣ Sauvegarder le PDF en artefact
      - name: Sauvegarder le PDF
        uses: actions/upload-artifact@v3
        with:
          name: CV
          path: cv.pdf
